### ISSUE TITLE
Ratio, episode-based measure observation results not appearing as expected

### ISSUE THREAD

**Issue by nmorasb** [projecttacoma/fqm-execution#176]
There are a few scenarios where we are not seeing the observation results that we would expect.
The first is for a ratio measure group where there is a single IP, and an observation on both the denominator and numerator.
We select the same function for both observations.
In the episode results for one episode, IP is true, Denominator is true and Numerator is true. The Denominator Observation is true but has two results in its observations array.
The Numerator Observation is false and has no results in its observations array.
We'd expect that the Numerator Observation result be true and to have a result when the Numerator passes. Instead it seems like the numerator observation result is being added to the denominator observation result array.
To verify which observation is for numerator and denominator we are going by the criteriaReferenceId, as that ties back to either the numerator or denominator populationId.
![image](https://user-images.githubusercontent.com/94391996/207425980-71180944-cbaf-40ee-a4f2-82bd66e72a5b.png)

The second scenario is ratio measure group with two IPs, and an observation on both denominator and numerator.
Again, we select the same function for both observations.
After execution again we'd expect one observation result for the denominator and one for numerator. (This is even more important in this case as denominator and numerator have separate IPs.)
Instead, we see both results on the denominator observation.
![image](https://user-images.githubusercontent.com/94391996/207422040-2efb6c75-e177-4ffc-8907-cb9c488fb3db.png)

Another episode for the same test doesn't appear to have any observation result even though the second IP and associated Numerator both pass. The Numerator Observation has a false and no observations array:
![image](https://user-images.githubusercontent.com/94391996/207424829-dc88f3f7-9770-4490-9f20-86c40ce5c279.png)

We'd expect the Numerator Observation here to have a true result and contain the result of the observation function.

Bundles for these scenarios are attached to this issue. Please let me know if any other information is needed or if we can help explain the scenarios any better.
Thanks!
[ratio-encounter-1ip.zip](https://github.com/projecttacoma/fqm-execution/files/10221392/ratio-encounter-1ip.zip)
[ratio-encounter-2ips.zip](https://github.com/projecttacoma/fqm-execution/files/10221393/ratio-encounter-2ips.zip)

**Comment by mgramigna** [comment]
Hi @nmorasb, thanks for the issue.

I think this is the first case we've seen that uses the same observation function for both the numerator and denominator observations. Right now, when recording results for an episode's observation, we would only check the criteriaExpression to ensure we're recording on the right one. But in the cases you've provided, the criteriaExpression might not always be unique for a given measure observation.

I think we should be able to also check the `criteriaReferenceId` property now that it is defined on population results to ensure we are recording results on the right measure observation.

I've logged an issue for this in our backlog, and will let you know when it's resolved.

**Comment by nmorasb** [comment]
Sounds good and thank you! Let me know if there's any other info we can provide to help!

**Comment by mgramigna** [comment]
Fixed in [v1.0.3](https://github.com/projecttacoma/fqm-execution/releases/tag/v1.0.3)
