### ISSUE TITLE
Ratio, episode-based measure observation results, for same function, not appearing correctly

### ISSUE THREAD

**Issue by gregory-akins** [projecttacoma/fqm-execution#187]
After upgrading to 1.0.3 (measure bundle and test case are in the attached tar.gz file)

We are executing a testcase where denominator and numerator results in incorrect "results"

With fqm-execution 1.0.2, this scenario results in correct results for Denom, but no results for Num

Now, with fqm-execution 1.0.3, this scenario results in incorrect results for Denom and correct results for Num

In this case, the IPP is where encounter is in a period, the DENOM is equal to IPP.  The NUMER is where Encounter.status == finished

So, for this test case, all Encounters are in the period.  So IPP = 3 & DENOM = 3.  Only one Encounter (Encounter 1) have a status of finished, so NUMER should = 1

There are Observations for DENOM & NUMER where each Observation is fun3 ( which is hardcoded to = 3)

We expect the results to show measure observation matches for denom & numer on Encounter 1 and measure observation matches for denom only for Encounter 2 & 3

The results for this execution show Encounter 1 matches as expected on denom & num as expected 

![image](https://user-images.githubusercontent.com/76972395/213247404-150ee517-6d01-41b3-8e01-0356ed4dc5ff.png)

However, for Encounter 2 & 3 (which should match denom, but not numer), the results show

![image](https://user-images.githubusercontent.com/76972395/213247788-6d625fc6-4388-452e-840b-366523849f60.png)

[measure_files.tar.gz](https://github.com/projecttacoma/fqm-execution/files/10448855/measure_files.tar.gz)

**Comment by mgramigna** [comment]
Thanks for the issue, @gregory-akins. This is probably related to some work we did to address #176, and we just might need to apply the same logic we did there in other places in the code.

We just planned a new sprint today, and this issue is at the top of the priorities. Will let you know when it is resolved/released

**Comment by mgramigna** [comment]
Fixed in https://github.com/projecttacoma/fqm-execution/releases/tag/v1.0.6
