### ISSUE TITLE
Calculations are not accurate to "seconds" in Condition.onsetDateTime

### ISSUE THREAD

**Issue by RohitKandimalla** [projecttacoma/fqm-execution#241]
### Summary
When I have a patient whose "Condition.onSetDateTime" is less than the Measurement Period End date, the calculations don't seem to be accurate. 

The test patient should pass denominator exclusion when Condition.onSetDateTime = "2024-12-31T23:59:59.000Z" as that meets the timing criteria 'starts on or before end of measurement period'. The test case does not pass until I change the time to 23:59:00 or earlier on 12/31 - having the time of 23:59:01 fails. Screenshots of CQL logic and test case resource can be found in the attached external ticket.

MADiE is using CalculationOptions to override MP start and end dates. 

Measurement Period start date: 2024-01-01T00:00:00.000+00:00
Measurement Period End date: 2024-12-31T23:59:59.999+00:00

MeasureBundle: 
[measureBundle.txt](https://github.com/projecttacoma/fqm-execution/files/11531450/measureBundle.txt)
[patientBundle.txt](https://github.com/projecttacoma/fqm-execution/files/11531451/patientBundle.txt)

Also, the [documentation](https://projecttacoma.github.io/fqm-execution/#/?id=calculating-an-ecqm:~:text=Promise%3CCalculatorTypes.ValueSetOutput%3E-,Calculation%20Options,-The%20options%20that) says that the measurement period should be in YYYY-MM-DD format. but looks like it does calculations to the last minute but doesn't take seconds into consideration. 

#### External Tracking Ticket
https://oncprojectracking.healthit.gov/support/browse/BONNIEMAT-1481

**Comment by RohitKandimalla** [comment]
Awesome, Thank you @mgramigna

**Comment by mgramigna** [comment]
This issue has been resolved and released in [v1.2.0](https://github.com/projecttacoma/fqm-execution/releases/tag/v1.2.0)

Updated documentation for allowed formats of measurement period input to fqm-execution can be found [here](https://projecttacoma.github.io/fqm-execution/#/?id=calculation-options)

In short, any value adhering to the [FHIR datetime format](https://www.hl7.org/fhir/datatypes.html#dateTime) should now be supported.
