### ISSUE TITLE
Coverage has been updated for a measure

### ISSUE THREAD

**Issue by mcmcphillips** [projecttacoma/fqm-execution#263]
### Summary
Updates to FQM execution appear to have modified the coverage of an existing measure from 100% to 85% and measure developers are requesting an explanation as to why this may have happened.

#### External Tracking Ticket
https://oncprojectracking.healthit.gov/support/browse/BONNIEMAT-1525

### Expected Behavior
Updates to fqm-execution would not modify existing coverage of a measure

### Inputs (e.g. Measure Bundle, Patient Bundle, CQL Library)
![image](https://github.com/projecttacoma/fqm-execution/assets/84744653/817d0a13-3dcf-404b-a82f-0880c2c76bb4)

[CMS349FHIR-v0.0.001-FHIR4 (2) (2).zip](https://github.com/projecttacoma/fqm-execution/files/12032422/CMS349FHIR-v0.0.001-FHIR4.2.2.zip)

**Comment by laclark22** [comment]
@mcmcphillips Could you please provide patient bundles for this issue? Our team has no ability of replicating this without the patients being used.

**Comment by hossenlopp** [comment]
@mcmcphillips This JSON appears to be a MongoDB export of a bunch of data. We will need JSON FHIR patient bundles to reproduce and debug this in our environment.

I took a peek at this measure in MADiE. It seems the SDEs are what is causing the coverage to not be 100%. Is it possible that the measure developer recently added SDEs to the measure and did not expect them to affect coverage?

**Comment by mcmcphillips** [comment]
@hossenlopp 
Sorry, let me get back to you

**Comment by mcmcphillips** [comment]
@hossenlopp 

I've provided the testcase bundles, measure bundle, and valusets. Let me know if I can provide any more information.

[CMS349ValueSets.txt](https://github.com/projecttacoma/fqm-execution/files/12043048/CMS349ValueSets.txt)
[CMS349TestCaseBundles.txt](https://github.com/projecttacoma/fqm-execution/files/12043049/CMS349TestCaseBundles.txt)
[CMS349MeasureBundle.txt](https://github.com/projecttacoma/fqm-execution/files/12043050/CMS349MeasureBundle.txt)


I have also posed the question to the measure developers on ONC jira and will update here accordingly
