### ISSUE TITLE
Procedure is not highlighted

### ISSUE THREAD

**Issue by RohitKandimalla** [projecttacoma/fqm-execution#271]
### Summary
MADiE team received a Helpdesk ticket, where user is trying to test a Procedure resource, but found out that highlighting is not as expected. 

<img width="807" alt="image" src="https://github.com/projecttacoma/fqm-execution/assets/57495404/2ed39d70-e901-4618-8678-31fb10dffb71">
Note: These definitions are created for testing purpose and are different from what User added. I did follow STU4.1.1 documentation 
https://hl7.org/fhir/us/qicore/STU4.1.1/StructureDefinition-qicore-procedure.html

#### External Tracking Ticket
[BONNIEMAT-1544](https://oncprojectracking.healthit.gov/support/browse/BONNIEMAT-1544)

### Expected Behavior
Define "Test 1" and "Test 2" are to be highlighted as Green.

### Inputs (e.g. Measure Bundle, Patient Bundle, CQL Library)
[PatientBundle.txt](https://github.com/projecttacoma/fqm-execution/files/12284253/PatientBundle.txt)
[MeasureBundle.txt](https://github.com/projecttacoma/fqm-execution/files/12284254/MeasureBundle.txt)

**Comment by hossenlopp** [comment]
Thank you for including the measure and patient bundles.

The logic highlighting is correct here. The coding in the procedure on the patient does not match what is expected by the measure. The measure expects a code with the `system` attribute being `http://hl7.org/fhir/sid/icd-10` but the Procedure in the patient bundle uses `http://www.cms.gov/Medicare/Coding/ICD10`. Please instruct the user to change the `system` in either the measure or the test case data. FYI, it seems that `http://www.cms.gov/Medicare/Coding/ICD10` is used by VSAC for ICD-10.
