### ISSUE TITLE
Calculation issue: few CQL clauses are not highlighted in green

### ISSUE THREAD

**Issue by adongare** [projecttacoma/fqm-execution#279]
### Summary
Some of the CQL clauses not being included in the highlighting. Please refer screenshot attached. Test patient [NUMERPassPop2_PainAssessDuringRadTx.json.zip](https://github.com/projecttacoma/fqm-execution/files/12528427/NUMERPassPop2_PainAssessDuringRadTx.json.zip) and measure bundle [CMS157FHIR.json.zip](https://github.com/projecttacoma/fqm-execution/files/12528424/CMS157FHIR.json.zip) is attached as well.  
<img width="1113" alt="Screenshot 2023-09-05 at 5 08 48 PM" src="https://github.com/projecttacoma/fqm-execution/assets/23436747/e7b162dd-6b87-4ede-a2f8-bea156bca24e">

 
#### External Tracking Ticket
https://oncprojectracking.healthit.gov/support/browse/BONNIEMAT-1597

### Expected Behavior
Group/population criteria 2 is expected to have 100% coverage. It shows 98%. I'm guessing some of the clauses are missing from highlighting/coverage calculation.  

### Inputs (e.g. Measure Bundle, Patient Bundle, CQL Library)
Measure & library bundle-  [CMS157FHIR.json.zip](https://github.com/projecttacoma/fqm-execution/files/12528424/CMS157FHIR.json.zip)
Patient Bundle:  [NUMERPassPop2_PainAssessDuringRadTx.json.zip](https://github.com/projecttacoma/fqm-execution/files/12528427/NUMERPassPop2_PainAssessDuringRadTx.json.zip)
 

### Relevant Calculation Options (e.g. Measurement Period, meta.profile Validation)

- includeClauseResults: false
- trustMetaProfile: true
- measurementPeriodStart
- measurementPeriodEnd

### cql-to-elm Version Used for Measure Logic Translation (if known)
v2.11.0

### Any Additional Info
The issue is for group/population criteria 2. It doesn’t have 100% coverage. The user is expecting to have 100% coverage for it. I tried debugging in fqm-execution a bit, and found that some of the CQL clauses might be missing from the coverage calculation. Especially the one shown in the above screenshot(red colored) doesn’t end up in the evaluated patient context. I've also included all test cases if needed  [CMS157FHIR-v0.0.005-FHIR4-TestCases 2.zip](https://github.com/projecttacoma/fqm-execution/files/12528705/CMS157FHIR-v0.0.005-FHIR4-TestCases.2.zip)
When I ran all test cases this is what I got in highlighting, so lil bit confusing if above screenshot is an issue or this screenshot:
<img width="1231" alt="image" src="https://github.com/projecttacoma/fqm-execution/assets/23436747/b236b2c4-a53d-4b73-b0f7-906d84028884">

**Comment by laclark22** [comment]
Hello, this issue has been fixed in our latest release of fqm-execution. Please refer to the release notes here https://github.com/projecttacoma/fqm-execution/releases/tag/v1.3.0

**Comment by adongare** [comment]
thank you so much, @laclark22!
