### ISSUE TITLE
Please test version 3.2 of CQL to ELM translator 

### ISSUE THREAD

**Issue by juliet-rubini** [projecttacoma/fqm-execution#283]

**Comment by birick1** [comment]
@juliet-rubini - We don't expect an issue with this version of the translator, but the team needs to do some investigation into best approaches for testing the updated translator.

**Comment by birick1** [comment]
We investigated various options over the last month and had conversations with stakeholders over possible solutions to test the engine post translator updates.  While investigating, we also tried to apply options under consideration to tickets that were filed.  

We found with the various moving parts that we would need to add manual processes to what we hoped to be automatic regression testing post translator updates.  The aspiration with this ticket was to reduce/eliminate manual checks extant in the prior workflow process, but the addition of needed manual steps in our testing didn't result in a net reduction.  So, after further discussion we are going to revert to the prior ticketing workflow, and we don't expect further tickets like this one.

In closing this ticket, version 3.2 of the translator was incorporated in MADiE and testing was done.
