### ISSUE TITLE
Coverage Highlighting Issue

### ISSUE THREAD

**Issue by sb-cecilialiu** [projecttacoma/fqm-execution#290]
### Summary
There seems to be some coverage highlighting issue which is supposed to be resolved with the newest execution v1.3.2.? For example, from the attached measure and test cases, when we run all the test cases, it shows the NoBetaBlockerOrdered.medication is not covered, however, when we run the individual test cases (BetalBlockerNotOrderedPR, and BetaBlockerNotOrderedMR), NoBetaBlockerOrdered.medication in “Beta Blocker Therapy for LVSD” shows covered and highlighted.

#### External Tracking Ticket
https://oncprojectracking.healthit.gov/support/browse/BONNIEMAT-1617

### Expected Behavior
Run all the test cases should show NoBetaBlockerOrdered.medication covered and highlighted

### Version or Commit
v.1.3.2 (NOTE: the problem exists with v.1.3.1 as well)

### Inputs (e.g. Measure Bundle, Patient Bundle, CQL Library)
[CMS144FHIR-v0.0.000-FHIR4.zip](https://github.com/projecttacoma/fqm-execution/files/13281685/CMS144FHIR-v0.0.000-FHIR4.zip)
[CMS144FHIR-v0.0.000-FHIR4-TestCases.zip](https://github.com/projecttacoma/fqm-execution/files/13281688/CMS144FHIR-v0.0.000-FHIR4-TestCases.zip)

### cql-to-elm Version Used for Measure Logic Translation (if known)
v2.11.0

**Comment by sb-cecilialiu** [comment]
NOTE: cql-to-elm Version Used is: v.3.2.0 instead.

**Comment by sb-cecilialiu** [comment]
NOTE 2: the external tracking ticket should be: https://oncprojectracking.healthit.gov/support/browse/BONNIEMAT-1627

**Comment by p9g** [comment]
If you extract the ELM XML from the Library resources in the measure export you attached, it shows 
`<annotation translatorVersion="3.3.2" ...`

**Comment by elsaperelli** [comment]
Hi @sb-cecilialiu !

Thank you for submitting this issue and providing the necessary data for our team to look into this. Upon initial investigation, we believe that this is an issue in the coverage highlighting and how we handle the `.medication` choice type. We have created a task to look into this issue and will be prioritizing it in our upcoming sprint.

**Comment by sb-cecilialiu** [comment]
@elsaperelli Thank you so very much for the quick feedback!

**Comment by sb-cecilialiu** [comment]
Thank you so much for the update!
