### ISSUE TITLE
Update the Highlighting UI for Covered/Passing/Failing statements

### ISSUE THREAD

**Issue by cybiggs** [projecttacoma/fqm-execution#297]
**Which fqm-execution feature is this request related to?**
Coverage highlighting, pass/fail highlighting

**Describe the solution you'd like**
We use the HTML blocks returned from fqm-execution to display the highlighting (coverage and pass/fail) in our test cases in MADiE.  Currently this seems to be how the UI is designed:
•	Not Covered – black font, no highlighting
•	Covered – dark blue font, light blue highlighting
•	Pass – dark green font, light green highlighting
•	Fail – dark red font, light red highlighting

Unfortunately this is not 508 compliant in our application because there needs to be something other than just color difference to call out the differences between each state.

Our UI Team has proposed the following:
•	Not Covered – black font, no highlighting, **no underline**
•	Covered – dark blue font, light blue highlighting, **no underline**
•	Pass – dark green font, light green highlighting, **single underline**
•	Fail – dark red font, light red highlighting, **double underline**

**Additional context**
n/a

**Comment by birick1** [comment]
Hi @cybiggs - a resolution is planned for v1.4.0 with a tentative release date of 4/12/24.
