### ISSUE TITLE
Coverage 97% with alias not covered

### ISSUE THREAD

**Issue by sb-cecilialiu** [projecttacoma/fqm-execution#318]
### Summary
For some reasons, the Test Coverage percentage keeps is standing at 97%. I have looked at the logic coverage page and everything appears to be covered except the alias of one of the definitions (see attached screenshot). 

#### External Tracking Ticket
(https://oncprojectracking.healthit.gov/support/browse/MADIE-2065)

### Expected Behavior
Should be 100%

### Version or Commit
Translator v3.14.0
fqm-execution 1.5.0

### Inputs (e.g. Measure Bundle, Patient Bundle, CQL Library)
[ColorectalCancerMeasureFHIR4-v0.0.022-FHIR4 (1).zip](https://github.com/user-attachments/files/17588423/ColorectalCancerMeasureFHIR4-v0.0.022-FHIR4.1.zip)
[ColorectalCancerMeasureFHIR4-v0.0.022-FHIR4-TestCases (1).zip](https://github.com/user-attachments/files/17588428/ColorectalCancerMeasureFHIR4-v0.0.022-FHIR4-TestCases.1.zip)
![MADiE_Question2](https://github.com/user-attachments/assets/868f02e8-3e80-446c-92c1-19937ad01ecf)

### Relevant Calculation Options (e.g. Measurement Period, meta.profile Validation)
{
    includeClauseResults: false,
    trustMetaProfile: true,
    buildStatementLevelHTML: true,
    measurementPeriodStart: 1/1/2024,
    measurementPeriodEnd: 12/31/2024,
}

### cql-to-elm Version Used for Measure Logic Translation (if known)
v3.14.0

### Any Additional Info
It seems like there was a similar issue (https://github.com/projecttacoma/fqm-execution/issues/285), but we are still having the issue.

**Comment by lmd59** [comment]
@sb-cecilialiu , Thanks for providing your measure and test cases. I've tested the coverage on fqm-execution 1.5.0, and it looks like this is a drop in coverage introduced with the v3.14.0 translator updates. https://github.com/projecttacoma/fqm-execution/pull/314 addresses the changes in coverage for v3.14.0-translated measures, and I've confirmed it brings this measure/Test case set back up to 100% coverage. We plan to include this update in our next release.
